import { BRAND_LOGO, BRAND_NAME } from './brand';

export const products = [
  {
    id: 1,
    title: 'Chegodilu',
    price: 149,
    rating: 4.8,
    category: 'Pindi Vantalu',
    image: BRAND_LOGO,
    description: 'Crispy ring-shaped rice flour snacks with sesame, cumin, and a gentle chilli kick.',
    origin: 'Andhra traditional kitchen',
    note: 'Best with evening tea',
    inStock: true,
  },
  {
    id: 2,
    title: 'Murukulu',
    price: 169,
    rating: 4.9,
    category: 'Pindi Vantalu',
    image: BRAND_LOGO,
    description: 'Classic spiral murukulu fried to a crisp bite with rice flour and roasted gram notes.',
    origin: 'Village-style recipe',
    note: 'Family snack pack',
    inStock: true,
  },
  {
    id: 3,
    title: 'Sakinalu',
    price: 219,
    rating: 4.8,
    category: 'Festival Specials',
    image: BRAND_LOGO,
    description: 'Traditional festive sakinalu with a light crunch, sesame aroma, and hand-shaped finish.',
    origin: 'Telugu festival kitchens',
    note: 'Festival favorite',
    inStock: true,
  },
  {
    id: 4,
    title: 'Chekkalu',
    price: 159,
    rating: 4.7,
    category: 'Savory Snacks',
    image: BRAND_LOGO,
    description: 'Thin, crunchy rice flour crisps seasoned with chilli, curry leaves, and roasted lentils.',
    origin: 'Andhra homes',
    note: 'Extra crunchy',
    inStock: true,
  },
  {
    id: 5,
    title: 'Ariselu',
    price: 249,
    rating: 4.9,
    category: 'Sweet Specials',
    image: BRAND_LOGO,
    description: 'Traditional jaggery and rice flour sweets finished with sesame for a rich festive taste.',
    origin: 'Harvest festival recipe',
    note: 'Jaggery sweet',
    inStock: true,
  },
  {
    id: 6,
    title: 'Bellam Gavvalu',
    price: 189,
    rating: 4.7,
    category: 'Sweet Specials',
    image: BRAND_LOGO,
    description: 'Shell-shaped gavvalu coated in jaggery syrup for a crisp outside and homely sweetness.',
    origin: 'Grandmother-style batch',
    note: 'Kid-friendly sweet',
    inStock: true,
  },
  {
    id: 7,
    title: 'Karam Pusa',
    price: 139,
    rating: 4.6,
    category: 'Savory Snacks',
    image: BRAND_LOGO,
    description: 'Fine crunchy strands with a spicy masala finish, perfect for mixing or snacking directly.',
    origin: 'Tea-time snack counter',
    note: 'Spicy batch',
    inStock: true,
  },
  {
    id: 8,
    title: 'Ribbon Pakoda',
    price: 159,
    rating: 4.8,
    category: 'Savory Snacks',
    image: BRAND_LOGO,
    description: 'Wide ribbon-style pakoda with a crisp texture and balanced chilli-garlic flavor.',
    origin: 'South Indian snack recipe',
    note: 'Crisp packed',
    inStock: true,
  },
  {
    id: 9,
    title: 'Boondi Mixture',
    price: 179,
    rating: 4.7,
    category: 'Savory Snacks',
    image: BRAND_LOGO,
    description: 'Savory boondi blended with nuts, curry leaves, sev, and spice for a complete snack bowl.',
    origin: 'Festival snack mix',
    note: 'Party pack',
    inStock: true,
  },
  {
    id: 10,
    title: 'Sunnundalu',
    price: 299,
    rating: 4.9,
    category: 'Sweet Specials',
    image: BRAND_LOGO,
    description: 'Urad dal laddus with ghee and sugar, made in the classic Telugu home style.',
    origin: 'Traditional sweet kitchen',
    note: 'Ghee-rich sweet',
    inStock: true,
  },
  {
    id: 11,
    title: 'Nuvvula Laddu',
    price: 229,
    rating: 4.8,
    category: 'Sweet Specials',
    image: BRAND_LOGO,
    description: 'Sesame and jaggery laddus with a nutty aroma and naturally rich festive sweetness.',
    origin: 'Sankranti favorite',
    note: 'Sesame jaggery',
    inStock: true,
  },
  {
    id: 12,
    title: 'Ragi Murukulu',
    price: 189,
    rating: 4.7,
    category: 'Millet Snacks',
    image: BRAND_LOGO,
    description: 'Millet-based murukulu with ragi flour for an earthy flavor and satisfying crunch.',
    origin: 'Millet kitchen',
    note: 'Ragi blend',
    inStock: true,
  },
  {
    id: 13,
    title: 'Jonna Chekkalu',
    price: 179,
    rating: 4.6,
    category: 'Millet Snacks',
    image: BRAND_LOGO,
    description: 'Jowar-based chekkalu with a rustic bite, mild spice, and crisp finish.',
    origin: 'Deccan millet recipe',
    note: 'Jowar snack',
    inStock: true,
  },
  {
    id: 14,
    title: 'Minapa Garelu Mix',
    price: 129,
    rating: 4.7,
    category: 'Homemade Staples',
    image: BRAND_LOGO,
    description: 'Ready-to-use urad dal mix for making soft garelu with a traditional home taste.',
    origin: 'Home batter mix',
    note: 'Quick prep',
    inStock: true,
  },
  {
    id: 15,
    title: 'Palli Karam Podi',
    price: 119,
    rating: 4.8,
    category: 'Homemade Staples',
    image: BRAND_LOGO,
    description: 'Roasted peanut spice powder for rice, idli, dosa, and everyday Telugu meals.',
    origin: 'Andhra podi blend',
    note: 'Meal companion',
    inStock: true,
  },
];

export const categories = [
  { id: 1, name: 'Pindi Vantalu', image: BRAND_LOGO },
  { id: 2, name: 'Savory Snacks', image: BRAND_LOGO },
  { id: 3, name: 'Sweet Specials', image: BRAND_LOGO },
  { id: 4, name: 'Festival Specials', image: BRAND_LOGO },
  { id: 5, name: 'Millet Snacks', image: BRAND_LOGO },
  { id: 6, name: 'Homemade Staples', image: BRAND_LOGO },
];

export const testimonials = [
  {
    id: 1,
    name: 'Anusha Reddy',
    role: 'Home Baker',
    text: `${BRAND_NAME} tastes close to the snacks we grew up eating at home. The murukulu stayed crisp even after delivery.`,
    avatar: BRAND_LOGO,
  },
  {
    id: 2,
    name: 'Ravi Kumar',
    role: 'Festival Host',
    text: 'The sakinalu and ariselu were packed neatly and made our festival table feel complete.',
    avatar: BRAND_LOGO,
  },
  {
    id: 3,
    name: 'Meghana Priya',
    role: 'Working Parent',
    text: 'I keep their chekkalu and karam pusa at home for tea-time snacks. The flavor is simple, fresh, and familiar.',
    avatar: BRAND_LOGO,
  },
];

export const benefits = [
  {
    id: 1,
    title: 'Traditional Recipes',
    description: 'Prepared with familiar Telugu home-style methods and time-tested ingredient combinations.',
    icon: 'Sprout',
  },
  {
    id: 2,
    title: 'Small-Batch Freshness',
    description: 'Snacks are made in focused batches so they keep their aroma, texture, and crunch.',
    icon: 'Leaf',
  },
  {
    id: 3,
    title: 'Careful Packing',
    description: 'Each order is packed to protect delicate sweets and crispy snacks during delivery.',
    icon: 'BadgeCheck',
  },
  {
    id: 4,
    title: 'Festival Ready',
    description: 'Order family packs, gifting packs, and everyday snack boxes for special occasions.',
    icon: 'Truck',
  },
];
